name: Deploy to Minecraft Server

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Copier les fichiers vers le serveur Minecraft
        run: |
          rsync -av --exclude='.git*' --exclude='.github*' ./ "/DATA/AppData/crafty/servers/f9805209-174c-4e1a-b8c5-64a6c491d727/world/datapacks/MapAventure"
